import json
import urllib.request
import urllib.error

BASE_URL = "http://localhost:5001/api"

def get_auth_token():
    url = f"{BASE_URL}/auth/login"
    data = json.dumps({"email": "admin@mis.local", "password": "Admin@12345"}).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req) as resp:
        res = json.loads(resp.read().decode())
        return res["data"]["token"]

def test_alerts_engine():
    token = get_auth_token()
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {token}"
    }

    print("[TEST] 1. Testing POST /api/alerts/scan (Automated Inventory Health Scan)...")
    req = urllib.request.Request(f"{BASE_URL}/alerts/scan", data=b"{}", headers=headers, method="POST")
    with urllib.request.urlopen(req) as resp:
        res = json.loads(resp.read().decode())
        assert res["success"] is True
        print(f"[OK] Scan executed successfully: {res['message']} (Total active alerts: {res['totalActiveAlerts']})")

    print("[TEST] 2. Testing GET /api/alerts...")
    req = urllib.request.Request(f"{BASE_URL}/alerts", headers=headers)
    with urllib.request.urlopen(req) as resp:
        res = json.loads(resp.read().decode())
        assert res["success"] is True
        counts = res["counts"]
        print(f"[OK] Fetched alerts. Total: {counts['total']}, Critical: {counts['critical']}, Warning: {counts['warning']}")
        assert len(res["data"]) > 0, "Expected at least one alert generated by scan"
        target_alert = res["data"][0]
        alert_id = target_alert["_id"]

    print(f"[TEST] 3. Testing PUT /api/alerts/{alert_id}/resolve (Resolve single alert)...")
    req = urllib.request.Request(f"{BASE_URL}/alerts/{alert_id}/resolve", data=b"{}", headers=headers, method="PUT")
    with urllib.request.urlopen(req) as resp:
        res = json.loads(resp.read().decode())
        assert res["success"] is True
        assert res["data"]["isResolved"] is True
        print(f"[OK] Alert {alert_id} marked as resolved.")

    print("[TEST] 4. Testing PUT /api/alerts/resolve-all (Batch resolve remaining)...")
    req = urllib.request.Request(f"{BASE_URL}/alerts/resolve-all", data=b"{}", headers=headers, method="PUT")
    with urllib.request.urlopen(req) as resp:
        res = json.loads(resp.read().decode())
        assert res["success"] is True
        print("[OK] Batch resolution succeeded.")

    print("\n=======================================================")
    print("ALL PHASE 7 BACKEND TESTS PASSED SUCCESSFULLY (100%)!")
    print("=======================================================")

if __name__ == "__main__":
    test_alerts_engine()
